fixed scripts, configured other build servers

diff --git a/bin/build-package b/bin/build-package
--- a/bin/build-package
+++ b/bin/build-package
@@ -32,10 +32,11 @@ ubuntu: lucid precise\n\
 COMPONENT_MAIN="main"
 COMPONENT_NIGHTLY="nightly"
 REPOS_SERVER="packages.mydomain.org"
+PACKAGES_WITHOUT_OTHERMIRROR="keyring"
 
 test -z $1 && { echo "usage: $(basename $0) [<subpath>/]<git-project> {main,main/<codename>,nightly,nightly/<codename>} [<git-checkout>]"; exit -1; }
 
-PREFIX=$(echo $0 | cut -d"-" -f1)
+PREFIX=$(echo `basename $0` | cut -d"-" -f1)
 test -f ~/.buildscripts/$PREFIX.conf && . ~/.buildscripts/$PREFIX.conf || { echo "$0 has no valid context prefix..."; exit -1; }
 
 set -ex
@@ -86,40 +87,6 @@ set_vars() {
 	return 0
 }
 
-clear_pkgdist() {
-
-	# pkgdist directory cleanup
-	cat "$PROJECT_DIR/BUILDS_FOR" | egrep -v '(^$|^#.*$)' | while read line; do
-		l_DIST="$(echo $line | cut -d":" -f1 | tr [A-Z] [a-z])"
-		CODENAMES="${CODENAMES:-$(echo $line | cut -d":" -f2- | tr [A-Z] [a#-z])}"
-		echo "$DISTS_SUPPORTED" | grep $l_DIST >/dev/null && {
-			for l_CODENAME in $CODENAMES; do
-				if [ "x$EXTRA_ARCHS_ONLY" = "x" ]; then
-					for l_ARCH in amd64 i386; do
-						mkdir -p "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH"
-						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.changes"
-						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.upload"
-						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.build"
-						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.dsc"
-						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.tar.gz"
-						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/*.deb"
-					done
-				fi
-				for l_EXTRA_ARCH in $EXTRA_ARCHS; do 
-					mkdir -p "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH"
-					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.changes"
-					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.upload"
-					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.build"
-					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.dsc"
-					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.tar.gz"
-					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/*.deb"
-				done	
-			done
-		}
-	done
-	return 0
-}
-
 prepare_workspace() {
 	# in any case remove the BUILDS_FOR file
 	rm -f "$PROJECT_DIR/BUILDS_FOR"
@@ -145,16 +112,61 @@ prepare_workspace() {
 	return 0
 }
 
+clear_pkgdist() {
+	# pkgdist directory cleanup
+	cat "$PROJECT_DIR/BUILDS_FOR" | egrep -v '(^$|^#.*$)' | while read line; do
+		l_DIST="$(echo ${line/: /:} | cut -d":" -f1 | tr [:upper:] [:lower:])"
+		l_CODENAMES="${CODENAMES:-$(echo ${line/: /:} | cut -d":" -f2- | tr [:upper:] [:lower:])}"
+		echo "$DISTS_SUPPORTED" | grep $l_DIST >/dev/null && {
+			for l_CODENAME in $l_CODENAMES; do
+
+				# in case we build a special CODENAME (squeeze, wheezy, lucid, ...) do skip
+				# the wrong distribution here...
+				test -z $CODENAMES || echo $line | grep $CODENAMES || break
+
+				if [ "x$EXTRA_ARCHS_ONLY" = "x" ]; then
+					for l_ARCH in amd64 i386; do
+						mkdir -p "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH"
+						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.changes"
+						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.upload"
+						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.build"
+						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.dsc"
+						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/$PROJECT_*.tar.gz"
+						rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH/*.deb"
+					done
+				fi
+				for l_EXTRA_ARCH in $EXTRA_ARCHS; do 
+					mkdir -p "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH"
+					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.changes"
+					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.upload"
+					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.build"
+					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.dsc"
+					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/$PROJECT_*.tar.gz"
+					rm -f "$PKGDIST/$l_DIST/$l_CODENAME/$l_EXTRA_ARCH/*.deb"
+				done
+			done
+		}
+	done
+	return 0
+}
+
 build_packages() {
 	# use pbuilder for building all variants of this package
 	cat "$PROJECT_DIR/BUILDS_FOR" | egrep -v '(^$|^#.*$)' | while read line; do
-		l_DIST="$(echo $line | cut -d":" -f1 | tr [A-Z] [a-z])"
-		CODENAMES="${CODENAMES:-$(echo $line | cut -d":" -f2- | tr [A-Z] [a-z])}"
+		l_DIST="$(echo ${line/: /:} | cut -d":" -f1 | tr [:upper:] [:lower:])"
+		l_CODENAMES="${CODENAMES:-$(echo ${line/: /:} | cut -d":" -f2- | tr [:upper:] [:lower:])}"
 		echo "$DISTS_SUPPORTED" | grep $l_DIST >/dev/null && {
-			for l_CODENAME in $CODENAMES; do
+			for l_CODENAME in $l_CODENAMES; do
+
+				# in case we build a special CODENAME (squeeze, wheezy, lucid, ...) do skip
+				# the wrong distribution here...
+				test -z $CODENAMES || echo $line | grep $CODENAMES || break
+
 				TEMP_DIR="$(mktemp -d --tmpdir=$TEMP_BASE)"
 				mkdir -p "$TEMP_DIR/$PROJECT"
 				chmod 2770 "$TEMP_DIR" -Rf
+
+				cd "$PROJECT_DIR"
 				git clone --local "$PROJECT_DIR" "$TEMP_DIR/$PROJECT/"
 				cd "$TEMP_DIR/$PROJECT"
 				git checkout $CHECKOUT || git checkout master
@@ -178,47 +190,45 @@ build_packages() {
 				# modify changelog for this build
 				dch --distribution $VERSION --force-distribution -l "+$l_CODENAME~$COMPONENT$DATE~$GITREV~build" "Auto-built $l_DIST $l_CODENAME package for $REPOS_SERVER repository."
 				mkdir -p $PKGDIST/$l_DIST/$l_CODENAME/{amd64,i386}
-				OTHERMIRROR="deb http://$REPOS_SERVER/$l_DIST $l_CODENAME $COMPONENT"
+				OTHERMIRROR=""
+				echo $PACKAGE_WITHOUT_OTHERMIRROR | grep $PROJECT >/dev/null || OTHERMIRROR="deb http://$REPOS_SERVER/$l_DIST $l_CODENAME $COMPONENT"
+				
 				[ "x$USE_SUDO" != "xyes" ] && {
 					[ "x$EXTRA_ARCHS_ONLY" = "x" ] && {
 						cat debian/control | egrep 'Architecture.*(all|any|amd64)' >/dev/null && {
-							DIST=$l_DIST CODENAME=$l_CODENAME ARCH=amd64 $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult "$PKGDIST/$l_DIST/$l_CODENAME/amd64"
+							DIST=$l_DIST CODENAME=$l_CODENAME ARCH=amd64 $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult "$PKGDIST/$l_DIST/$l_CODENAME/amd64" 0<&-
 						}
 						cat debian/control | egrep 'Architecture.*(any|i386)' >/dev/null && {
-							DIST=$l_DIST CODENAME=$l_CODENAME ARCH=i386  $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult "$PKGDIST/$l_DIST/$l_CODENAME/i386"  -- --binary-arch
+							DIST=$l_DIST CODENAME=$l_CODENAME ARCH=i386  $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult "$PKGDIST/$l_DIST/$l_CODENAME/i386"  -- --binary-arch 0<&-
 						}
 					}
 					for extra_arch in $EXTRA_ARCHS; do
 						mkdir -p "$PKGDIST/$l_DIST/$l_CODENAME/$extra_arch"
 						cat debian/control | egrep "Architecture.*(any|$extra_arch)" >/dev/null && {
-							DIST=$l_DIST CODENAME=$l_CODENAME ARCH=$extra_arch $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult "$PKGDIST/$l_DIST/$l_CODENAME/$extra_arch" -- --binary-arch
+							DIST=$l_DIST CODENAME=$l_CODENAME ARCH=$extra_arch $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult "$PKGDIST/$l_DIST/$l_CODENAME/$extra_arch" -- --binary-arch 0<&-
 						}
 					done
 				}
 				[ "x$USE_SUDO" = "xyes" ] && {
 					[ "x$EXTRA_ARCHS_ONLY" = "x" ] && {
 						cat debian/control | egrep 'Architecture.*(all|any|amd64)' >/dev/null && {
-							sudo DIST=$l_DIST CODENAME=$l_CODENAME ARCH=amd64 OTHERMIRROR="$OTHERMIRROR" $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult $PKGDIST/$l_DIST/$l_CODENAME/amd64
+							sudo DIST=$l_DIST CODENAME=$l_CODENAME ARCH=amd64 OTHERMIRROR="$OTHERMIRROR" $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult $PKGDIST/$l_DIST/$l_CODENAME/amd64 0<&-
 						}
 						cat debian/control | egrep 'Architecture.*(any|i386)' >/dev/null && {
-							sudo DIST=$l_DIST CODENAME=$l_CODENAME ARCH=i386  OTHERMIRROR="$OTHERMIRROR" $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult $PKGDIST/$l_DIST/$l_CODENAME/i386  -- --binary-arch
+							sudo DIST=$l_DIST CODENAME=$l_CODENAME ARCH=i386  OTHERMIRROR="$OTHERMIRROR" $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult $PKGDIST/$l_DIST/$l_CODENAME/i386  -- --binary-arch 0<&-
 						}
 					}
 					for extra_arch in $EXTRA_ARCHS; do
 						mkdir -p "$PKGDIST/$l_DIST/$l_CODENAME/$extra_arch"
 						cat debian/control | egrep "Architecture.*(any|$extra_arch)" >/dev/null && {
-						    sudo DIST=$l_DIST CODENAME=$l_CODENAME ARCH=$extra_arch OTHERMIRROR="$OTHERMIRROR" $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult "$PKGDIST/$l_DIST/$l_CODENAME/$extra_arch" -- --binary-arch
+							sudo DIST=$l_DIST CODENAME=$l_CODENAME ARCH=$extra_arch OTHERMIRROR="$OTHERMIRROR" $PDEBUILD --auto-debsign --debsign-k $GPG_KEY --buildresult "$PKGDIST/$l_DIST/$l_CODENAME/$extra_arch" -- --binary-arch 0<&-
 						}
 					done
 				}
-				cd -
 				rm -Rf "$TEMP_DIR"
 			done
-			echo
 		}
-		echo
 	done
-	echo
 	return 0
 }
 
@@ -226,9 +236,14 @@ upload_packages() {
 	# dupload the new packages to the reprepro repository
 	cd "$PKGDIST"
 	cat "$PROJECT_DIR/BUILDS_FOR" | egrep -v '(^$|^#.*$)' | while read line; do
-		l_DIST=$(echo $line | cut -d":" -f1 | tr [A-Z] [a-z])
-		CODENAMES=${CODENAMES:-$(echo $line | cut -d":" -f2- | tr [A-Z] [a-z])}
-		for l_CODENAME in $CODENAMES; do
+		l_DIST=$(echo ${line/: /:} | cut -d":" -f1 | tr [:upper:] [:lower:])
+		l_CODENAMES=${CODENAMES:-$(echo ${line/: /:} | cut -d":" -f2- | tr [:upper:] [:lower:])}
+		for l_CODENAME in $l_CODENAMES; do
+
+			# in case we build a special CODENAME (squeeze, wheezy, lucid, ...) do skip
+			# the wrong distribution here...
+			test -z $CODENAMES || echo $line | grep $CODENAMES || break
+
 			if [ "x$EXTRA_ARCHS_ONLY" = "x" ]; then	
 				for l_ARCH in amd64 i386; do 
 					cd "$PKGDIST/$l_DIST/$l_CODENAME/$l_ARCH"
@@ -251,8 +266,8 @@ upload_packages() {
 set_vars $@ && {
 	if [ "x$(basename $0)" = "x$PREFIX-build-package" ] || [ "x$(basename $0)" = "x$PREFIX-build+upload-package" ]; then
 		cd $PROJECT_DIR && pkgneedsbuild $CHECKOUT || [ "$FORCE_BUILD" -eq 0 ] && {
-			clear_pkgdist
 			prepare_workspace && {
+				clear_pkgdist
 				build_packages
 			}
 		}
